apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: clickhouse
    namespace: clickhouse
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: clickhouse-passwords
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            passwords.xml: ENC[AES256_GCM,data:swXyokCdzSw5tyNMNrVgZn6v04CYy3sTgrT4Ou5Cq+WDx4Jsyhf/9hLugSdLHbSTj2YiIAWbmeIr/UCKH5xAcMiqTcrFCJVmS92bq52Omoo6OHp4ASD9ItK4iQ7znCLM6jR4Cn6D1b2mnvELa30WDERiM55XsC3IDyP/sH63uVvBlW5KXQ4jFf1qN1pgB8YkAUqhptf9itmDQVCyfRhe84oENV6FROrP15j2+dQExGTLFEFq+3EjLmWPMr/tLoahgJixDklLuAJtRQSYe18FGVqdV9QQCH8OwCpM3iYXw1iYXY/NRNXnL4G+TNvbwhfKzeVzxirtKX4w/llwNYfAJW/LIMe95ad1YdtDTsRTehPBN7KlHS/msbu6BlMtRfNRznxYwrTwgxZmXMw8GjHvvmO35kBoO83j5suOpVZNWHJovsu8Z8/k0G/tuyFMgArCdXYIOAyi5Kf71PX06ikmcRq6IU95mYAz5gTbVxZY8LV7UHsVk/EUwK6WTCCjQKStcQe0T1TC5WnT0x0KJkOw/XlXpgsmAY0kXb6mhIThuto8UZJvXbuhq0iJdzWHTaZI/OtkVF/YbXKpLXeqYDMDJeqVGGgFjlg5hxuUAxCRiUGlRT1rmLw5iugkcQUcT3ydp//SJK7iipbBHdcPPFGTqtaAY5PV7eRdL17ciP3z3kw2VgoxY84HyHdxxs0glN1W2HIElPueMd/gYggnv56BIj6j0ZAuwCgczjGvLEZtMMopayp9arFv5PTdejI6UlEQNpIvXfmeeAogXxGoKwU/nvgMv3VMH5sEQB6nRfVJ4uqCu1ELBNl7QKXu1mBegzAPoYaCw7u+zVO/6XUppo7PV/2WfMzx9ms+yR2J5vJuzkEbTFWFLpPY/eb8cVz/hfXj7gVwmvOBLsVCCbd2T9i7k5Y4U4bZCgk7DMKhr0RV2tfX/WCQTUAO6jJHULZ6ZQI70itEpFqmTupUpdy+OId+CMpF+lW+2d7AUOeipzLRIjBRkmq2pZkqV5uA8B3hMFwxktgNbvgjFeueNRwTCRIpSCB0D2EziW8PJuchIvmMN1px4QM4Qz1k1WGtU2FPE4yMiBNcFmsay141sc/ZxCmzoJTNHgKX/Pafo/kc3mxxxdvFyR0Z41Fw/m9GKKHo7JVzKpbMUNOm0EoMh+JV3aqYfgeetwGAJn8zL12OrPQrKKA3oMN/xtUzyhsZEAO6agL55zv+sKFbdBdMRiDmXx16oeUbOJpGQ3Obme7K09Tm,iv:Dd1Y6zE4gNFnm5SdupaUB6M+OBltT+Eb0v5mjIpXB5g=,tag:/D6qEOsWYkWGh0UfTw5RGg==,type:str]
        - name: clickhouse-default-password
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            password: ENC[AES256_GCM,data:LakKLtbAA4scObI8zY+Qfd1PAlEJ7o31rZWLNjpUosw=,iv:jvXsYZT0p6mJHB/0QcxtXM5jFL4nTwGbr0gjDAO3yuE=,tag:vvdK6HvEAiuo6+NQvpjJ/g==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWjA0T0FScHVLYXFvQ2E4
            NWJnUkd5Zm9aOGxhbVlENmthY2tJOVA2a1ZrCmR6RmZwVlJaUVk0dHlJZkNRYWtV
            YWpLZjM1RDlVM0tYU01sK2ZCVG5maXcKLS0tIC82M2J3dk50TGQ5a3gzNWk0b01u
            dnhic3ljbmkyVjQ2RWQreXZ3WXArMkEK6ZK+uuJ+O3czIm0ghSiCXwYFAIvU1FwU
            XGAypLM3uNI06VPcK6ce03WQynOMJupNX3gOVx9enEOSO6Gi4sEObw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNzh2ZmFwWTRXQVNEeXhO
            NDNMd0tDUERYd0VueU5Fb3RCb3pGYTF4aUY0CkpQR1A0L2pDQUtHSnZhQ014a3Y2
            WFlRN0svQnFLY2dmTi9KSElWZ0k5djgKLS0tIG52UW1jUU5kdUMrczB2UmZIU2k5
            VEdXU2ZmVVM4dXNLRWgzT04rQnlZK3cKNqeQTaZcpxRsG3WC30nv5PbnqIs9cC2P
            DcQeupyvtEBL8FpfBoybaGKx8ZPMk+CPp9+pca2Fza3RPgTmn5un6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T22:47:39Z"
    mac: ENC[AES256_GCM,data:uaNKa6f/e5aFs1w9sabPatLyjot8yPFpZEooNfK1l1+YqG26fxQPdyjVA2YB1o8Ac4whTmTYsR+Eeo9LRiuzNQNy0cUFKY7Jd/UDIVnetwWgjg2UDXEzPFDs2CEkjpCLMhoyNmsuKhdfrueBoNjQ7nHaqt+UBjr2xxULOewduRw=,iv:BFdbMRWZLOhleN7d53phoNR9LRipT1+5dQ9Wi4B4opg=,tag:cyBUPXjWs81a64qCANnsZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
