apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cert-manager-sopssecret
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-api-token
          type: Opaque
          stringData:
            api-token: ENC[AES256_GCM,data:6GrAAyFOqQH8VIwbYx3gq38jS/w2MvWIAa0QwhZ5YMnBrV6Sz/MnGA==,iv:tP0HBEF53jy4wriN1MoX518Ir9Fg9KkhB9NSAu5ofBc=,tag:FjogLfIp8Pn0KqNFD1Qx7A==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZGJBQ1hyZVphY1o0SWZl
            NVNqZDNyVHREYkFPQUFuZWZHbzk3Y3BybG5BCkRQNW5udjFFQnRaNjFic2RlcGsz
            WlFFSzVMTW0rVWkraUFVeHdvYXlZS3MKLS0tIHFZWVg4eGdjdnVqNWFDUmJZMURV
            QngwcGtnUjJ4dnJ2MW5jNnQxNHdPZXMKu1xmR0ZWq+KhHMIcnASKDmjEQgDvzYXY
            XaVaYZeBvb8vRBWNewzVogUzM6tpH9kRepPkcChiC88QDUFNVdujjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEemFCbDh5dk9aN3RqVFJl
            dUUyVWhqRUlOc0FIa0M5ZEI1VnN6RzFuQ3pNCmM4NGlCUVlKbWoyQ05JaDBlallG
            VE1SdUpuWDdLM1hxN1JzNHZYcWhiT1kKLS0tIDk1bHc1TkFNVzBwMFpxQUtrQVoy
            TEFBdE4yMnpTMzJ3TExJREl3MnYrMmMKDwBUfYsQbK4gZzs+afMwHUvhh93FTzeI
            /RRK6MmDJqKIA4CIsmEkljoHtv1NN2NxWFRfGWELczfq15nbHjabrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T22:27:41Z"
    mac: ENC[AES256_GCM,data:jpdIA1oZKcox4QcSKJJA6iG1dZXN8rPA3vVBoonMLOdx3U5EOADtauAaICXfogpAvgctlTFInuuyJNoEwaS7to8vm5cJR7xd5aIXRTc+qDVX+tyUsKoqz6HP/uL9Tlm+VUdJJOnzHQKHHB9wwvKSgN+MESew7LaBLOIMIM2DpQk=,iv:e3iD0bwoWbGmkffLYlPG+nsHCjpHYR52LawTzszjdbU=,tag:ZMVXrWZMjzXq4E9sOOUmcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
