apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-sopssecret
    namespace: authentik
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: authentik-postgres
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            POSTGRES_DB: ENC[AES256_GCM,data:MSlKNJShv3gM,iv:7kfX1pjkZB5qp7DE35cOzyowVCTza2D4sbEE0Wzj+MU=,tag:jcFpPnBKXA5EPo9acLfweA==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:bqvyTdH9FjHm,iv:7Obo+xUtzdTUkwrZ/8M/08NM/C6DK/UWbeIesARwV/Q=,tag:a9Je10fEXtzmBssRp51RbA==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:roLQspgI8NArTzyiqJP2ZXdOqFJ30NlFHCbqNq4eOJND3SlO,iv:GtjEVIK6cDGbOSArwe19iLtCu0XzzNh6JGIbFPTqqAY=,tag:x7Q3dpkpxGpEBkYNJ+0nkQ==,type:str]
        - name: authentik-core
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:hqqz8K2pApBb8X0HYUFOJOAn+wjWIZrcRRmwtC3WD85LvOscNATak+ihQgvOSqt1PPAXXFK5m8U8A8//,iv:ytlalVWicl1diYvyLH137tBwaEjPY2LEE1fovXvaiRY=,tag:vyFgCN8Woqd5tO0odS3qRg==,type:str]
            AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:PIb/fHnm+CLlbPLNqICuYpO5Uey5uFtt/3L/89IApNdT19JC,iv:ObtaDx4g8kEVV4pSEgC2RzrReh9ESUYPMWebNm/6JKc=,tag:mozu3shZEKvFvkEh6rSzaw==,type:str]
            AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:z+QGeG7KmMiiOo0sLV18XjqpnLR+lxQb,iv:2J/zxFjrswLbX1VUioxPjkq9jbW3mlj/Xw+3n5slzIc=,tag:NIKT55hxLzY1cZXDpu35wQ==,type:str]
            AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:rT5EhcQr0pNt8hKeC0uzEar9EU7h,iv:1lDrQIZIs/BvjpQwaGGc398k2Lc0scwU/yNy735UGUM=,tag:vk9AJM+rydqc4o8SjnBlmw==,type:str]
            NGARVEY_INITIAL_PASSWORD: ENC[AES256_GCM,data:Cq4evbdPUQ974pnnjaAV6iAi,iv:csrgDvFAv2nmn6KucGii4ej3C7L8oNQqULauXujbP3E=,tag:2QjhJXJedypR3GEtc6BtnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV3AyRGFScFFXZTRHOTVu
            cnpOUGw0by9VVUhpcjFNN24rcjBxdnZkR3dBCkxka2dxNmVnNisvNHZENmgvaTZh
            aHRob1BvWnViTmJVKzlPU2xhVkhyZDAKLS0tIGdQR3hRRzhGQnhrREsrWHloREtv
            SUR5aWhSUTNRRFlBV2JGbGdHbFJ4Y00KdwlVTH/OlOjcCSicGfdc8d8bA0F6+tuc
            e5JhL2kR9yYV2cHh1ojKIqsQFRjAm82yPct8nUW51riYN6UUjA9CRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTCtJOGN4S0htaUdnMmR2
            d29pYW1LdVE3WlFMcjFKVTFKTGZoei9HQUFNClRVRHNIVE9DNDN1c2QzV2Y2R0ly
            eU9PL2ErR2NCY2g2Uk4zakRkd1pQQU0KLS0tIDA1MU16bVptVTJHTjhqdGQ0citY
            cVBMMzBQWHIrSnNvOTF3UmRocmYyWHMK3VjMEe0sXYgYYENVOPYwwY/Ei2aI598m
            MzvFwoSM6bHLKRrWIYwg2118WYIo3I4OOmkFnFpzDfRm5YOUZu+TpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T20:39:20Z"
    mac: ENC[AES256_GCM,data:y2NkukIleD7Xzs8DgElYg1yqrwczw77+QzdvsqFMaRwjFdRBUuj39qVHiISMSfZYRg+poTDn1oTNTXWVQumeoDOOlLBsh3wwe+jSIyYAx+91nCkjAJg4iSCsKFY8i2yrV/B6pgtidmUrbu9BK40fkwCWLNw+W9oAhDskUY7Lcuk=,iv:Rtauvb/hwI0uVzkhHPwTU2co+OHpbZo8cOHP1JKiQcI=,tag:u2z93nf7eFYxqEm6amC6vg==,type:str]
    version: 3.13.1
