apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-caddy
  namespace: opencloud
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
data:
  Caddyfile: |
    {
      auto_https off
      admin off
    }
    :443 {
      tls /certs/tls.crt /certs/tls.key
      reverse_proxy http://127.0.0.1:9200
    }
