apiVersion: v1
kind: Service
metadata:
  name: opencloud
  namespace: opencloud
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  type: ClusterIP
  selector:
    app: opencloud
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
