apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: opencloud-sopssecret
    namespace: opencloud
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: opencloud-storage
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            GATEWAY_S3_ACCESS_KEY: ENC[AES256_GCM,data:VelAIkuoPjMEk/64/04PbfhQh1Y=,iv:0dfJrmCbN0JYf8KZsUnP1Ws8HqrgsKeEWos5UzS1bhg=,tag:A0EXDJCA8ZJwpyJ0CJsTDQ==,type:str]
            GATEWAY_S3_SECRET_KEY: ENC[AES256_GCM,data:l0NsazldkUvFFCRSc6cXSoqsxeOR9scWhqqUongPlkH+egSaSZfRCQ==,iv:WWuewBP0ILv77bTt/Y4VmEgi5So5+xeSvIfovY3mjYo=,tag:+Go2/R8JMcje0T9qagB/Kw==,type:str]
            IDM_ADMIN_PASSWORD: ENC[AES256_GCM,data:z93o2pyyp4LztSzdlNs85CvtgzPHIyp7frFw9PL7YUXj13zhgnEFPlhwm/C+YISU,iv:n/YcR+MOeHeoKkms1uz7KWx0aeC/MzjCqrQnUfx8Zco=,tag:l5vMhYtVuZ/vlz9CsHsYUg==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNlQzbHdtTGFwRjFHcU5x
            NkRTMytvZURtZ3RvazNsTFJHS3V3d3AySlJNCjRHaHdlblBGbXBGRk9zMUVMTXBw
            ZnZlczNHR3dGTDc0RSs1NTA2aElUajAKLS0tIG5ML3ViK2xkcVhVamxQNDB3SFRZ
            MVhxT0l2QW8wVUYweVlibjZ6aUxWWlkKuKxo+GI6QhpGPnupIWylVkloDyBl+jKf
            mctc08BjogqW/I5H4SB1e5ZrQErAq4a/hgD68mt8drCzWluzZldpgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TGY2K0ZEVEdEVXZPczdl
            Qk1GNVNqSTd1cStyM1BSMW9DcDFjai9DcUYwCk4rZDB5emNsSjEwV0FvYW8zZktZ
            Qmx6TzBvUXF4N0hjMkxnYUFLZklicVEKLS0tIERrd1FFTFI2QnBLRlRaNWxPWDMz
            NEVremZRbldUcXNoeVRXdHVjYzRmTlUK/B9Tutlbsk4db7Im6h7quBVZb3v7OFYZ
            /1HbuJigPgujU0qVcuBPRlm29ZypE8B3sNAyBmIyQyP/CwrzSZ7drQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:39:43Z"
    mac: ENC[AES256_GCM,data:JXp2dfkK8fv2zjNLNGJagEsDf6eLK4MGm7G6OCutMT2KxyWKUHVKNwDoff4u1ebm+ScYRtRM1AHeVH1Xhr6EF/fKzyUfUgJkMo5MKNYXM2RFJVPeEFU2Eh07IdiX0JZwxP7870jIxGY8vhH5B/T21l8h1++9P89WMqrpVUE0FsU=,iv:tRurWBSd0fyKSz/QWOOOwq75y5nshZRLCtkv2oxR6us=,tag:6w1dH5FpiX5MLLPVHF8Okw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
