apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tailscale-operator-sopssecret
    namespace: tailscale
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: operator-oauth
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            client_id: ENC[AES256_GCM,data:QaTl9lUYs2+Qd4W+v4Ug5BM=,iv:6SAjbWKEOAxHaXqXquX2VBAEgK7eBc4VN/OatLk5ww8=,tag:IN5kuRoYgseQvRllyCEhKg==,type:str]
            client_secret: ENC[AES256_GCM,data:r1rfc1lQsMTWOPRANjmw6Dq7OnCGzOqSciQHDCo/+lPVH+orE0Yfu/yS7iQhZiGYZJkgy4U9AtdsWGFXrkWstQ==,iv:oVbb37akjxOOt/Sdmj4OoFn4xSvOAarDV8XiwRYU1OQ=,tag:bAxV/sENCWonaU7cBFvUOw==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YjAxYjNqcGdkaEFBRW9H
            UytCVzVxY2tVb2xVMk9OQ2MwWkQwZFpuVlRzCnQ1WkRHOW91anB6TkxIbHFXbG1R
            aVc5M29hcS8rSTVKNWIraWtNOFRZOTAKLS0tIFh3QVFCY29EdU5rZ2YrbzJ4ckVt
            WlJrWjFYNUgvbkIreUpqUUhrcGYrY0UKoWY9n6zSxkj+f5BDoVfARQdyqgeKeStI
            8jLK6FKTFkXidc0aMEunYCUKm6ZlC6oqGOChEfKx7KOjTCZMT/Ytww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MC8yU0VCb3NDSWh4eE1G
            ZENsSU1Ra1o2Sm5hY29VQkpaR0VZN2hTeXlzCkIrcFpxWW1mckxMUjhRck5wSnBm
            NVMyMWMzKy9HNDVpeFI5MG1qeEZXWEUKLS0tIHlqc1dhWHpqZTZTZEg1TWRQTjNs
            UjNaZkk0N1JCT3g4eXpZVSttdGtUUDQKOambL/+/shzIUyz5AXkF1UNFbDUBWBDO
            EEgTbtPM/TZzIP+XA3C1dHRz5YDoQSazQHe92mKlXoO1KOFDAzMNyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T14:22:47Z"
    mac: ENC[AES256_GCM,data:JuoCCgCE6jMJaDv6HTGAGMbxkOQvNHlZObHsw83DbvxRFrYKnQJUH0Vi4f0Lvz/8aG5+CoA9wIgyqAhh2C5BvDe0XIMkMZEDz+8s7dc6GVnx6T90wUz6bz6hLdNiX0Jz1oNMBQv5pRGhpv2u8DZIiOJgVx+qm1ZQzTsqIwPstDc=,iv:ZtHxTuoCiYqT2+Fe8nT4S785Gw/yKuoqNej/V2/w9/4=,tag:DV4YZvrCIqlGdlM/jSKbhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
