apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-dns-data
  namespace: acme-dns
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-wffc
  resources:
    requests:
      storage: 1Gi
