apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mimir-sopssecret
    namespace: mimir
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: mimir-storage
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            GATEWAY_S3_ACCESS_KEY: ENC[AES256_GCM,data:W5zq7tqiGgCeTu1fnwKeD8Cg1X4=,iv:AreerNLq+QJCqth5WeWMlawzF2cbMG0qHNDFs0VRNRE=,tag:gKfZcXkJOCkT9aT5nu2+QQ==,type:str]
            GATEWAY_S3_SECRET_KEY: ENC[AES256_GCM,data:cwrGnpwI+HPIZyJfI1grZDu16k52czTyrhGwND9JObj+TUTyxN8a4g==,iv:EMxFDZiVb+J8U/nsck8DoUF6k5/uQHa/dftBSpAmLqw=,tag:UsV02KbzB+9yfnwqywZf6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQXJlckVPRkpQRmVMWU5I
            aUdPOUU5akM2L1ZWQ296dlV4SU9YbS9oaVJZCjdmQzBlR0NwclV4Mit5ZjIyMnlR
            V0ZBLzdSVUczbUc3aTZYd1VuVkVNT2MKLS0tIHR3UXBLR3JFQURVM1FaN0FrdzRn
            eER6b3l4TWE1cG9STDU3Rk5COXhGL3MKbkGhPGuDTL7vCSl6oJ3RBHJu4fGJIiso
            CLT4mM8pis8b4RGRwHa3f75SUBF+GjE0jOBzAFSCwE4Jkcj1bxQMzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dUJOSWI3c3EvKzhsYXh3
            d1E0aEg3djhUK0lNK1BRcmx4YlpRQmNVM1RnCmZZZVFuNnNMQU92RkNWYk1oT1ZR
            UEdVL0xpU1E0eEtsQnk1S0xYbllIVzAKLS0tIHYyelE1RzhWdGVOSGs4alFOTzlx
            N2w3enp6OFV3Y21OdlVTbHRuOElZbGcKnRxohzYJ7ppzRLME1KZ7yxCSHH25DLlH
            YyQvr5ZebJrVb5noHC9OY+RaLBI4D92eN7fHIZQlBGukI+62KkHO8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T03:25:40Z"
    mac: ENC[AES256_GCM,data:0tBMpA1BKZZAzCWiv9WnGPNoJy8cPk+JyEhUL0zr36d3GEGKx+kerX3H+Nwzkzqm6eU7Bc8i2bCCQ2ST3aw145FGWqrnIUO+JChDACJP3tbM65lN7v3At3+5upPQDbi873ZyBFdnVIkDuB+kkTrjtOLTv/3LnJSryE+zyRkswyw=,iv:/XWDY/41M4lM7Czker5SKYaM4mUkCcNqaDbyFwcGuts=,tag:LzAB8DKHuATIECU16uM50w==,type:str]
    version: 3.13.1
