apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: smb-media-pv-jellyfin
  resources:
    requests:
      storage: 1000Gi
