apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jellyfin-sopssecret
    namespace: jellyfin
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: smb-secret
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            username: ENC[AES256_GCM,data:bmaj6t03Jiw=,iv:J7FT97eGPt2HHhhXBItzlzCVjqPW2VN0V657Ii9L2K0=,tag:v5KOkCXSOKofV8n420/S8w==,type:str]
            password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVTkzQmk1bUxJaEltWGc4
            MEVxTDgxcCtTMVVEa0c1VkJZcnRFdTY0YlRJCmc5VGs5ajVyMmhrTzlDNGI2dlZB
            MEx5V2J4NEFuOVZNVk9ydzVwbVo3V1UKLS0tIEN6eE1VL1lTNkhtV05FM3lFZEh5
            SE5vN3FOVmh4TGk3RXN2TUEwUHNXUVkKXa559Fo9Ik2t56lV4Xt6WUdTAm5M0t/z
            7N8utmGwLaFfVmF1bhPLy+1YCQR2mI4eY01d3O8oS2Ococ6gF8+hpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdCtUcHMrQjBUeXhjb1Y3
            amM4dGZjZzg5eWZLV09sWXJ5T3ozQkZwbFhBCkNHQStFVm1ONXJISmdMWE1yOUlo
            MkNtY3Z0eUZSS3dQOFJKc1BYZmRWR3MKLS0tIE94MnBvdGg0UEVIUTI0MG5zMFRx
            d0Q4OFBqaUc0UVBTV2h3ait2VkU4c1UKpdy6TmYV4mfzpM2kUIch5PGkIGo0W7j+
            P1n+AzBSciQtBzjP2hScaN8cz1CSK1VSJcHLCqaSBtYvZaUq/8YTeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T19:09:37Z"
    mac: ENC[AES256_GCM,data:up2BpdzSGwBamBIkeXkFyqgRcoFFQjCmQ8KeAw6fnwN+1dGjf+gKsUiewY2SutuPkrSs+4tFTtBPmOjlS5z3iK4IR69MZ4alBElhS7ji0JYY673SDA+50GuNXS6Tqb1/CH0sIFsTffGBmUDm1eif25UhR6g9pB9VOwuvkPKED9s=,iv:8DHtlRv6nLF5uQ5YAll6HkgQgMjICnGD5plz98cytSE=,tag:2dvyw/eETemNQDfNCU/2jQ==,type:str]
    version: 3.13.1
