apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: grafana
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-wffc
  resources:
    requests:
      storage: 2Gi
