apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  backupTargetURL: nfs://microatx.home.arpa:/slow/backups/longhorn
  pollInterval: 5m0s
