apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-garage-sopssecret
    namespace: longhorn-system
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: longhorn-garage-secret
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VcVl6UqW2hK+KUKtJe1XfpTV7w0le81l+Cg=,iv:2o/YUPB9zQhtzS03VULFctQZHFB139bptcNP8Bzfm6U=,tag:kwDPD2c9XEAxq0XV+ZO9lQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:i3XJ0K0aQBPijZZOrjFyuHw5cJNbvRURAYDZlY5KJuhUlVPIAmh7ydiK9vDd1TXCJzOza4UBxTQVL8e1f+RqQw==,iv:mPugh3FsWLdWRdVxt3d/3s6zpG8lUaFTjiqrlrT1M5Q=,tag:QTBtHFDr6clzWtUjJHBa+Q==,type:str]
            AWS_ENDPOINTS: ENC[AES256_GCM,data:yipU5V7WGdReL+hoEJ3hU75Z/xIiKz4mNFa92w==,iv:PApbWBx4LNDGt8b+tZ2ni6O2gM+rqlY/bsxUrbWA+j4=,tag:R87BU+G6OmkoAfk0/gHJBw==,type:str]
            VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:qX9Ppco=,iv:b8O2QTy+7Qch6V2WXvhhzHN2Db+RKbT/xG5hb4FWqWQ=,tag:WevDtFkSbwvvcUbsiyinFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM2FQQUdHL0lvTDhtUSs3
            eDZJbWlVVk93SmgyQlNPN3Vrbm9DZDR6ZFU4CjUxbWNZMTAxMnJsVzFqVUpNcU1S
            UmxHVkFSYTBsaVAzYXVzVXlzYzUyYUkKLS0tIHBtek5GN3pjMENJTUg1OEF0dkJn
            ZkMrVXhabThUQzlWMzJSdkttNWwzQmcKAMaxh0mAelALPy/ecPxDU2JNMx3EuuGC
            zYYId8Ml2TzmFWKFZFFPI9TH0glwNKXCYROoZ7PQVXhglHq6imiFpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWCtTUFhodXBoUzd2NGRC
            L2pXMHV5a2ppbWlDTVJYeENqWDA3eEJOZ2pFCkN5Mis5K0NBUHd0cmNvTjZEdXo0
            VzdoSk96TFc1YUh1NDJxcDljbXVOeFkKLS0tIEgvOW16VTNoL0hoay85MHFhZkFV
            RWRCN2d1dStYWk41ZWJWMm1VS3JYaE0K8gZDs8L8/HcsAeruD4DXQC0lqGA5ztez
            wbW/t04IfXgLjLY7gegI7ZzrE8ito+YZhYQGGGFieXnv/aY51DKAIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T02:06:40Z"
    mac: ENC[AES256_GCM,data:DxpGxILndP6dAPVM7mxz2HzP/rsnqQwX62MHxLVcv3S8GFZl2NcPFI3qajtCmYhlStC8wH9tdn7siK8Ug0HkRCdvMJwYi0l3XDraPPoVKqReJBOG1Wvs8TIKZuruxJuAdSumUcPeAJqnrH3CX4Oj9kY5ITiDJZO//XgoZf7mkXw=,iv:Lk/35AaIuUFb/XmwbZgTZjTf4rXjGW97jNO/aeKpewo=,tag:U8r9x5uO9/tcTQ+QBXqdZA==,type:str]
    version: 3.13.1
