apiVersion: v1
kind: Service
metadata:
  name: trmnl-display
  namespace: trmnl-display
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  selector:
    app: trmnl-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 10.28.15.210
