apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-caddy
  namespace: temporal
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
data:
  Caddyfile: |
    {
      auto_https off
      admin off
    }
    :80 {
      redir https://{host}{uri} permanent
    }
    :443 {
      tls /certs/tls.crt /certs/tls.key
      reverse_proxy http://127.0.0.1:8080
    }
