apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: temporal
  namespace: temporal
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
    app.kubernetes.io/name: temporal
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
  endpoints:
    - port: metrics
      interval: 30s
