apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: anki-sopssecret
    namespace: anki
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: anki-credentials
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            SYNC_USER1: ENC[AES256_GCM,data:QuQ4o0Tmyjvw,iv:ftF4Ag/F4VhUOGoOMVS3qJrCOvRw+YSMHPDk5hErFj0=,tag:2NAAwjqWDgmAiN9wIX7EQw==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMWQ2OExkUnJxTldaU1JX
            MGR3bkgzZHdOSHdUaHk2ekx5b05Mbko1ZDJrCjc2L2pyNHBjN2J4Uk4xc05DZXJV
            clZ0OUFBanFFTCtFNXljVW1kWGRKU2sKLS0tIG90c0czb29xQmhMYXd5c3RzNEtD
            SC9UakxmTUxTaVA3MDZCN3VFdWJkSzQKfaibuwzRBVj+HVo05y4cr0Mh6f/f+M8s
            UA26aLknA96wPWHaqnxBgo3KG4iprjdyLTL2yReHXa6t3NhXi7DM9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z2YxdGFSaGpLeVZndk1N
            R1J1M0tCaHNBSlBDWGJ4c0VsYmlIaEVBY3lNCjBFTjZwMkNuRUZIemtGVTdGbVNW
            U0g1OGV4bzVzcm9ON0Fnbng4MEdVRW8KLS0tIHRsT0pBK1hWNFpUUzZMZVR2Zzd4
            V3orNFcvSjVUZ2JuRm4ybDhUbFhwdFUKKmFAzhyZgyIncCGm4TIB9/tYC87dkeVm
            zCIFhMYNqx5mhLKU8xBfLjFn69jBZX1S119l724/GYifrGqqqMJg5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T14:35:49Z"
    mac: ENC[AES256_GCM,data:ASPNbM+xqVSXloOCK8gC/srte71xeW0FWoDA5+61NS9O6kjiKVaaKT7j4tS3cKx0ha7vF6q247T2UEo1QN8EvO9KgyBGJmQJFPIpcWM4n7cQbyRRUMxO4zYBQQIzdz1zXOTJA2vHhnQVoc8YX+4RygOR9PiaCdRkax9yQRUTrAE=,iv:BnlhgLMqAgYYoLY3XAPy5KEDoXdiGnDdL98WId1XRis=,tag:FlksI35XDAOvuL5IfmgGmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
