apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: zot-sopssecret
    namespace: zot
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: zot-s3
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8EoRBIYOMCuudpm3wNjY88+sYFWn5U1AI2s=,iv:vhGSNdai9ChtjVdI+KLfFuHP1fC5NNFInhYR1Yj+2PU=,tag:LpDEUFVBVnDYx36lGZ9AeA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XDkSSTCbJsdrGD8mZw9RYfgGA7DAcWJGz7K4krO0XAFyKDVEc0+zokTlTY8VHBhIm4wkd290zmf2Fq6fk7rhug==,iv:lh+u1kOTNDQB8g6rlCjg5H4ID+DHHvDiOSb3G61DGls=,tag:6DMLc2V6X3BayKr6hWBrQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMUo5SVlCalFvSlpQd0RI
            ZmY4NHE4RTBxK0Q1NVNpbGxvR1RJdmZ0cFhNCmVQVUhjd0tFWUxSRHg4OVp6aFY0
            NnRHMGF0bTF1TU9OTElzSFUxMWk5bjQKLS0tIDBnbGlDK3MzWFppVGp2c3owYzRB
            cStFbkV2VmhKTUdXQkVEc0FRQ2F2bWcKBQlUAKTP4r1AM680KKmlcxNxS1KRI55T
            MGwoV87SpjcM32rL1Jqs5WNsHfav5pvhsJUgRScvd6L7JB8U2BkVaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaUR1ZCtseFdpZEN1WkVr
            THlBdkpES2pIM05kMXI4QUd3VlYyLzRCWUEwClp1bXpCVzBjcVNjQ2RFVWJWaENh
            MURWaWpBUUZqelRJc1dsKysvUEkxMkkKLS0tIE84c2tPRVZ3c3Z6dHpvN1dZMWNY
            TmJHSkUyVnNHa21KUXpSSmtpdVpGVGcKewBD3XD/tYikIvL5ocu5OyBY6iU9Cm7Y
            fOy0E6fW2Rb0PHvXg5Z4HuKXHy0dtXEtwsIR4BRcZfDPXOnPkSFjWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T21:19:39Z"
    mac: ENC[AES256_GCM,data:6V8mnW9cH7zfI1h+EZHx1MWM4qxquzeSnbQOYKl/bBHw1uV7cNLSJvTsD57+72npwFo/dOyijRMbLLrUKncQbm6DaTVlrDZrCjAbVaA4AFS72bvqw5Fyy13qfnsZhn1ktge/h84TyiXtV5HfBPyfmvTrn9NSUU10k3sdFQtS64M=,iv:aSi/2aleXyJfWvCrEP8EOdetyamN/wVHtZnu6KlRZEA=,tag:WF0vA9hNUHfgf5Pj/oAHOg==,type:str]
    version: 3.13.1
