apiVersion: v1
kind: Service
metadata:
  name: zot
  namespace: zot
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
  annotations:
    io.cilium/lb-ipam-ips: "2001:470:482f:2::5000"
spec:
  ipFamilies: [IPv6]
  ipFamilyPolicy: SingleStack
  selector:
    app: zot
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
  type: LoadBalancer
